//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DataEntitiesConnection : DbContext
    {
        public DataEntitiesConnection()
            : base("name=DataEntitiesConnection")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual ObjectResult<MobileChangeStation_Result> MobileChangeStation(Nullable<int> userID, Nullable<int> stationID)
        {
            var userIDParameter = userID.HasValue ?
                new ObjectParameter("UserID", userID) :
                new ObjectParameter("UserID", typeof(int));
    
            var stationIDParameter = stationID.HasValue ?
                new ObjectParameter("StationID", stationID) :
                new ObjectParameter("StationID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<MobileChangeStation_Result>("MobileChangeStation", userIDParameter, stationIDParameter);
        }
    
        public virtual int MobileGuestAttended(Nullable<int> contWinID, Nullable<System.DateTime> now)
        {
            var contWinIDParameter = contWinID.HasValue ?
                new ObjectParameter("ContWinID", contWinID) :
                new ObjectParameter("ContWinID", typeof(int));
    
            var nowParameter = now.HasValue ?
                new ObjectParameter("Now", now) :
                new ObjectParameter("Now", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("MobileGuestAttended", contWinIDParameter, nowParameter);
        }
    
        public virtual ObjectResult<MobileGuestListContests_Result> MobileGuestListContests(Nullable<int> stationID)
        {
            var stationIDParameter = stationID.HasValue ?
                new ObjectParameter("StationID", stationID) :
                new ObjectParameter("StationID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<MobileGuestListContests_Result>("MobileGuestListContests", stationIDParameter);
        }
    
        public virtual int MobileGuestListMarkDistributed(Nullable<int> contestID, Nullable<System.DateTime> now)
        {
            var contestIDParameter = contestID.HasValue ?
                new ObjectParameter("ContestID", contestID) :
                new ObjectParameter("ContestID", typeof(int));
    
            var nowParameter = now.HasValue ?
                new ObjectParameter("Now", now) :
                new ObjectParameter("Now", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("MobileGuestListMarkDistributed", contestIDParameter, nowParameter);
        }
    
        public virtual ObjectResult<MobileGuestListPeople_Result> MobileGuestListPeople(Nullable<int> contestID)
        {
            var contestIDParameter = contestID.HasValue ?
                new ObjectParameter("ContestID", contestID) :
                new ObjectParameter("ContestID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<MobileGuestListPeople_Result>("MobileGuestListPeople", contestIDParameter);
        }
    
        public virtual int MobileGuestRemoveAttended(Nullable<int> contWinID)
        {
            var contWinIDParameter = contWinID.HasValue ?
                new ObjectParameter("ContWinID", contWinID) :
                new ObjectParameter("ContWinID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("MobileGuestRemoveAttended", contWinIDParameter);
        }
    
        public virtual ObjectResult<MobileStationList_Result> MobileStationList(Nullable<int> userid)
        {
            var useridParameter = userid.HasValue ?
                new ObjectParameter("userid", userid) :
                new ObjectParameter("userid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<MobileStationList_Result>("MobileStationList", useridParameter);
        }
    }
}
